version: '2.2'
services:
    app:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - "5005:5000"
      volumes:
        - ./app:/code

    nginx:
      image: nginx:1.19.2
      volumes:
        - ./deploy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./deploy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
        - /tmp/logs/nginx/:/var/log/nginx/
      depends_on:
        - app
      ports:
        - 8080:80

    filebeat:
      image: elastic/filebeat:6.8.3
      volumes:
        - /tmp/logs/nginx:/var/log/nginx:ro
        - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
      depends_on:
        - kibana
        - elasticsearch
        - logstash
        - app
        - nginx

    logstash:
      image: logstash:7.17.9
      depends_on:
        - elasticsearch
      environment:
        XPACK_MONITORING_ENABLED: "false"
        ES_HOST: "elasticsearch:9200"
      volumes:
        - ./deploy/logstash.conf:/config/logstash.conf:ro
      command: logstash -f /config/logstash.conf

    elasticsearch:
      image: elasticsearch:7.17.9
      environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms265m -Xmx265m"
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1


    kibana:
      image: kibana:7.17.9
      container_name: kibana
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      depends_on:
        - elasticsearch